[package]
name = "ifrexsim/grid-pack"
description = "An easy way to create grid-type inventories."
version = "0.2.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
signal = "sleitnick/signal@2.0.1"
trove = "sleitnick/trove@1.1.0"